// Builds the M1 (Patient Summary) + M2 (Visit History) payload for the v2 PDF engine.
// Translates clinical data via the existing translate-export edge function (24h cached),
// derives the at-a-glance counts and Clinical Highlights, deduplicates imaging studies,
// then POSTs to render-export-pdf.

import { supabase } from "@/integrations/supabase/client";
import type { VaultData } from "@/lib/pdfExport";
import type { Visit, ImagingLinkOverride } from "@/store/vaultStore";
import { SUPPORTED_LANGUAGES } from "@/lib/supportedLanguages";
import { dedupeImaging } from "@/lib/visitDedupe";

export type ProgressPhase = "translating" | "rendering" | "ready";

export interface PatientSummaryInput {
  data: VaultData;
  visits?: Visit[];
  imagingOverrides?: ImagingLinkOverride[];
  patient: {
    fullName: string;
    dob?: string;
    biologicalSex?: string;
    nationality?: string;
    bloodType?: string;
    chronicConditions?: string;
  };
  language: string;
  onProgress?: (phase: ProgressPhase) => void;
}

// ---------- Localised UI strings (extended for M2 — Visit History) ----------
type StringPack = {
  patientSummary: string;
  atAGlance: (n: number, c: number, y: number) => string;
  currentMedications: string;
  knownAllergies: string;
  chronicConditions: string;
  clinicalHighlights: string;
  none: string;
  page: (i: number, total: number) => string;
  footerNote: string;
  disclaimer: string;
  visitHistory: string;
  visitHistorySubtitle: string;
  reasonForVisit: string;
  investigations: string;
  findings: string;
  diagnosis: string;
  medicationsPrescribed: string;
  followUp: string;
  noVisits: string;
  // M3
  medicationsTitle: string;
  medicationsSubtitle: string;
  medColName: string;
  medColDose: string;
  medColFrequency: string;
  medColPrescriber: string;
  medColStarted: string;
  medColStatus: string;
  medActive: string;
  medInactive: string;
  noMedications: string;
  bloodResultsTitle: string;
  bloodResultsSubtitle: string;
  bloodColMarker: string;
  bloodColValue: string;
  bloodColRange: string;
  bloodColStatus: string;
  bloodColDate: string;
  bloodStatusNormal: string;
  bloodStatusFlagged: string;
  bloodStatusCritical: string;
  noBloodResults: string;
  imagingTitle: string;
  imagingSubtitle: string;
  imagingFinding: string;
  imagingNormal: string;
  imagingFlagged: string;
  noImaging: string;
};

const STRINGS: Record<string, StringPack> = {
  en: {
    patientSummary: "Patient Summary",
    atAGlance: (n, c, y) =>
      `This health record contains ${n} document${n === 1 ? "" : "s"} from ${c} ${c === 1 ? "country" : "countries"} spanning ${y} year${y === 1 ? "" : "s"}.`,
    currentMedications: "Current Medications",
    knownAllergies: "Known Allergies",
    chronicConditions: "Chronic Conditions",
    clinicalHighlights: "Clinical Highlights",
    none: "None recorded.",
    page: (i, total) => `Page ${i} of ${total}`,
    footerNote: "Generated by RinVita",
    disclaimer:
      "Generated by RinVita Health Intelligence. This document contains extracted health data and is not a substitute for original clinical records. RinVita is not a medical device. ICO Registration ZC123014.",
    visitHistory: "Visit History and Clinical Encounters",
    visitHistorySubtitle: "Structured summary of clinical letters, discharge summaries and consultations.",
    reasonForVisit: "Reason for visit",
    investigations: "Investigations",
    findings: "Findings",
    diagnosis: "Diagnosis",
    medicationsPrescribed: "Medications prescribed",
    followUp: "Follow-up",
    noVisits: "No clinical visit records extracted yet.",
    medicationsTitle: "Medications",
    medicationsSubtitle: "All medications recorded across uploaded documents and manual entries.",
    medColName: "Medication",
    medColDose: "Dose",
    medColFrequency: "Frequency",
    medColPrescriber: "Prescriber",
    medColStarted: "Started",
    medColStatus: "Status",
    medActive: "Active",
    medInactive: "Inactive",
    noMedications: "No medications recorded.",
    bloodResultsTitle: "Lab Results",
    bloodResultsSubtitle: "Most recent value per marker. Status indicators reflect reference ranges.",
    bloodColMarker: "Marker",
    bloodColValue: "Value",
    bloodColRange: "Reference range",
    bloodColStatus: "Status",
    bloodColDate: "Date",
    bloodStatusNormal: "Normal",
    bloodStatusFlagged: "Flagged",
    bloodStatusCritical: "Critical",
    noBloodResults: "No blood test results recorded.",
    imagingTitle: "Imaging Studies",
    imagingSubtitle: "Deduplicated by modality, region, facility and date.",
    imagingFinding: "Finding",
    imagingNormal: "Normal",
    imagingFlagged: "Flagged",
    noImaging: "No imaging studies recorded.",
  },
  ar: {
    patientSummary: "ملخص المريض",
    atAGlance: (n, c, y) => `يحتوي هذا السجل الصحي على ${n} مستند من ${c} دولة على مدى ${y} سنوات.`,
    currentMedications: "الأدوية الحالية",
    knownAllergies: "الحساسية المعروفة",
    chronicConditions: "الحالات المزمنة",
    clinicalHighlights: "الملاحظات السريرية",
    none: "لا يوجد.",
    page: (i, total) => `صفحة ${i} من ${total}`,
    footerNote: "تم إنشاؤه بواسطة RinVita",
    disclaimer:
      "تم إنشاؤه بواسطة RinVita Health Intelligence. هذه الوثيقة تحتوي على بيانات صحية مستخرجة وليست بديلاً عن السجلات السريرية الأصلية. RinVita ليست جهازًا طبيًا. تسجيل ICO ZC123014.",
    visitHistory: "سجل الزيارات واللقاءات السريرية",
    visitHistorySubtitle: "ملخص منظم للرسائل السريرية وملخصات الخروج والاستشارات.",
    reasonForVisit: "سبب الزيارة",
    investigations: "الفحوصات",
    findings: "النتائج",
    diagnosis: "التشخيص",
    medicationsPrescribed: "الأدوية الموصوفة",
    followUp: "المتابعة",
    noVisits: "لم يتم استخراج سجلات زيارات سريرية بعد.",
    medicationsTitle: "الأدوية",
    medicationsSubtitle: "جميع الأدوية المسجلة عبر المستندات والإدخالات اليدوية.",
    medColName: "الدواء",
    medColDose: "الجرعة",
    medColFrequency: "التكرار",
    medColPrescriber: "الواصف",
    medColStarted: "بدأ",
    medColStatus: "الحالة",
    medActive: "نشط",
    medInactive: "غير نشط",
    noMedications: "لا توجد أدوية مسجلة.",
    bloodResultsTitle: "نتائج فحوصات الدم",
    bloodResultsSubtitle: "أحدث قيمة لكل مؤشر. مؤشرات الحالة تعكس النطاقات المرجعية.",
    bloodColMarker: "المؤشر",
    bloodColValue: "القيمة",
    bloodColRange: "النطاق المرجعي",
    bloodColStatus: "الحالة",
    bloodColDate: "التاريخ",
    bloodStatusNormal: "طبيعي",
    bloodStatusFlagged: "مُعلَّم",
    bloodStatusCritical: "حرج",
    noBloodResults: "لا توجد نتائج فحوصات دم مسجلة.",
    imagingTitle: "دراسات التصوير",
    imagingSubtitle: "تمت إزالة التكرار حسب النوع والمنطقة والمنشأة والتاريخ.",
    imagingFinding: "النتيجة",
    imagingNormal: "طبيعي",
    imagingFlagged: "مُعلَّم",
    noImaging: "لا توجد دراسات تصوير مسجلة.",
  },
  es: {
    patientSummary: "Resumen del paciente",
    atAGlance: (n, c, y) =>
      `Este registro de salud contiene ${n} documento${n === 1 ? "" : "s"} de ${c} ${c === 1 ? "país" : "países"} a lo largo de ${y} año${y === 1 ? "" : "s"}.`,
    currentMedications: "Medicación actual",
    knownAllergies: "Alergias conocidas",
    chronicConditions: "Condiciones crónicas",
    clinicalHighlights: "Aspectos clínicos destacados",
    none: "Ninguno registrado.",
    page: (i, total) => `Página ${i} de ${total}`,
    footerNote: "Generado por RinVita",
    disclaimer:
      "Generado por RinVita Health Intelligence. Este documento contiene datos de salud extraídos y no sustituye los registros clínicos originales. RinVita no es un dispositivo médico. Registro ICO ZC123014.",
    visitHistory: "Historial de visitas y encuentros clínicos",
    visitHistorySubtitle: "Resumen estructurado de cartas clínicas, informes de alta y consultas.",
    reasonForVisit: "Motivo de la visita",
    investigations: "Pruebas realizadas",
    findings: "Hallazgos",
    diagnosis: "Diagnóstico",
    medicationsPrescribed: "Medicación prescrita",
    followUp: "Seguimiento",
    noVisits: "Aún no se han extraído registros de visitas clínicas.",
    medicationsTitle: "Medicación",
    medicationsSubtitle: "Toda la medicación registrada en documentos cargados y entradas manuales.",
    medColName: "Medicamento",
    medColDose: "Dosis",
    medColFrequency: "Frecuencia",
    medColPrescriber: "Prescriptor",
    medColStarted: "Inicio",
    medColStatus: "Estado",
    medActive: "Activo",
    medInactive: "Inactivo",
    noMedications: "Sin medicación registrada.",
    bloodResultsTitle: "Resultados de sangre",
    bloodResultsSubtitle: "Valor más reciente por marcador. Los indicadores reflejan los rangos de referencia.",
    bloodColMarker: "Marcador",
    bloodColValue: "Valor",
    bloodColRange: "Rango de referencia",
    bloodColStatus: "Estado",
    bloodColDate: "Fecha",
    bloodStatusNormal: "Normal",
    bloodStatusFlagged: "Marcado",
    bloodStatusCritical: "Crítico",
    noBloodResults: "Sin resultados de análisis de sangre.",
    imagingTitle: "Estudios de imagen",
    imagingSubtitle: "Deduplicados por modalidad, región, centro y fecha.",
    imagingFinding: "Hallazgo",
    imagingNormal: "Normal",
    imagingFlagged: "Marcado",
    noImaging: "Sin estudios de imagen registrados.",
  },
  fr: {
    patientSummary: "Résumé du patient",
    atAGlance: (n, c, y) =>
      `Ce dossier médical contient ${n} document${n === 1 ? "" : "s"} provenant de ${c} pays sur ${y} an${y === 1 ? "" : "s"}.`,
    currentMedications: "Médicaments actuels",
    knownAllergies: "Allergies connues",
    chronicConditions: "Affections chroniques",
    clinicalHighlights: "Points cliniques marquants",
    none: "Aucun enregistré.",
    page: (i, total) => `Page ${i} sur ${total}`,
    footerNote: "Généré par RinVita",
    disclaimer:
      "Généré par RinVita Health Intelligence. Ce document contient des données de santé extraites et ne remplace pas les dossiers cliniques originaux. RinVita n'est pas un dispositif médical. Enregistrement ICO ZC123014.",
    visitHistory: "Historique des visites et consultations cliniques",
    visitHistorySubtitle: "Résumé structuré des lettres cliniques, comptes rendus d'hospitalisation et consultations.",
    reasonForVisit: "Motif de la visite",
    investigations: "Examens réalisés",
    findings: "Constatations",
    diagnosis: "Diagnostic",
    medicationsPrescribed: "Médicaments prescrits",
    followUp: "Suivi",
    noVisits: "Aucune visite clinique extraite pour le moment.",
    medicationsTitle: "Médicaments",
    medicationsSubtitle: "Tous les médicaments enregistrés via les documents et les saisies manuelles.",
    medColName: "Médicament",
    medColDose: "Dose",
    medColFrequency: "Fréquence",
    medColPrescriber: "Prescripteur",
    medColStarted: "Début",
    medColStatus: "Statut",
    medActive: "Actif",
    medInactive: "Inactif",
    noMedications: "Aucun médicament enregistré.",
    bloodResultsTitle: "Résultats sanguins",
    bloodResultsSubtitle: "Valeur la plus récente par marqueur. Les indicateurs reflètent les plages de référence.",
    bloodColMarker: "Marqueur",
    bloodColValue: "Valeur",
    bloodColRange: "Plage de référence",
    bloodColStatus: "Statut",
    bloodColDate: "Date",
    bloodStatusNormal: "Normal",
    bloodStatusFlagged: "Signalé",
    bloodStatusCritical: "Critique",
    noBloodResults: "Aucun résultat sanguin enregistré.",
    imagingTitle: "Examens d'imagerie",
    imagingSubtitle: "Dédupliqués par modalité, région, établissement et date.",
    imagingFinding: "Constatation",
    imagingNormal: "Normal",
    imagingFlagged: "Signalé",
    noImaging: "Aucun examen d'imagerie enregistré.",
  },
};

function getStrings(lang: string): StringPack {
  return STRINGS[lang] || STRINGS.en;
}

// ---------- Derivations ----------
function computeCounts(data: VaultData): { documents: number; countries: number; yearsSpan: number } {
  const documents = data.documents.length;
  const countries = new Set(
    data.documents.map((d) => d.country).filter((c) => c && c.trim().length > 0),
  ).size;

  const allDates = [
    ...data.documents.map((d) => d.date),
    ...data.bloodResults.map((b) => b.date),
    ...data.imagingResults.map((i) => i.date),
  ]
    .filter(Boolean)
    .map((d) => new Date(d as string).getFullYear())
    .filter((y) => !Number.isNaN(y) && y > 1900);

  const yearsSpan = allDates.length === 0 ? 0 : Math.max(1, Math.max(...allDates) - Math.min(...allDates) + 1);

  return { documents, countries, yearsSpan };
}

function deriveHighlights(data: VaultData): string[] {
  const out: string[] = [];

  // Out-of-range blood markers, most recent first.
  const flagged = data.bloodResults
    .filter((r) => r.status === "flagged" || r.status === "critical")
    .sort((a, b) => (b.date || "").localeCompare(a.date || ""));

  for (const r of flagged.slice(0, 4)) {
    const dateBit = r.date ? ` on ${r.date}` : "";
    const rangeBit = r.range ? ` (reference ${r.range})` : "";
    out.push(`${r.marker} ${r.value} ${r.unit} — out of range${rangeBit}${dateBit}.`);
  }

  // Imaging findings flagged non-normal.
  const flaggedImaging = data.imagingResults
    .filter((i) => i.status === "flagged")
    .sort((a, b) => (b.date || "").localeCompare(a.date || ""));

  for (const img of flaggedImaging.slice(0, Math.max(0, 5 - out.length))) {
    const dateBit = img.date ? ` (${img.date})` : "";
    out.push(`${img.type} ${img.region} — ${img.finding}${dateBit}.`);
  }

  return out.slice(0, 5);
}

// ---------- Translation ----------
async function translateIfNeeded(data: VaultData, language: string): Promise<VaultData> {
  if (!language || language === "en") return data;
  try {
    const { data: result, error } = await supabase.functions.invoke("translate-export", {
      body: { payload: data, targetLanguage: language },
    });
    if (error) throw new Error(error.message || "Translation failed");
    return (result?.translated as VaultData) || data;
  } catch (err) {
    console.warn("translate-export failed, falling back to source data:", err);
    return data;
  }
}

// ---------- Public entry ----------
export async function generatePatientSummaryV2(input: PatientSummaryInput): Promise<Blob> {
  const { data, patient, language, onProgress } = input;

  onProgress?.("translating");
  const translated = await translateIfNeeded(data, language);

  onProgress?.("rendering");

  const counts = computeCounts(translated);
  const highlights = deriveHighlights(translated);
  const currentMeds = translated.medications
    .filter((m) => m.active !== false)
    .map((m) => ({ name: m.name, dose: m.dose, frequency: m.frequency }));
  const allergies = translated.allergies.map((a) => ({
    substance: a.substance,
    severity: a.severity,
    reaction: a.reaction,
  }));

  // M3: full medications table (including inactive), sorted active-first then by date desc.
  const medicationsTable = [...translated.medications]
    .sort((a, b) => {
      if (a.active !== b.active) return a.active ? -1 : 1;
      return (b.date || "").localeCompare(a.date || "");
    })
    .map((m) => ({
      name: m.name,
      dose: m.dose,
      frequency: m.frequency,
      prescriber: m.prescriber,
      facility: m.facility,
      date: m.date,
      active: m.active !== false,
    }));

  // M3: blood results — most recent value per marker.
  const byMarker = new Map<string, typeof translated.bloodResults[number]>();
  for (const r of translated.bloodResults) {
    const existing = byMarker.get(r.marker);
    if (!existing || (r.date || "").localeCompare(existing.date || "") > 0) {
      byMarker.set(r.marker, r);
    }
  }
  const bloodTable = [...byMarker.values()]
    .sort((a, b) => {
      // Critical → flagged → normal, then by marker name.
      const rank: Record<string, number> = { critical: 0, flagged: 1, normal: 2 };
      const ra = rank[a.status] ?? 3;
      const rb = rank[b.status] ?? 3;
      if (ra !== rb) return ra - rb;
      return a.marker.localeCompare(b.marker);
    })
    .map((r) => ({
      marker: r.marker,
      value: r.value,
      unit: r.unit,
      range: r.range,
      status: r.status,
      date: r.date,
    }));

  // M3: deduped imaging studies.
  const dedupedImaging = dedupeImaging(translated.imagingResults, input.imagingOverrides || []);
  const imagingTable = dedupedImaging
    .sort((a, b) => (b.date || "").localeCompare(a.date || ""))
    .map((i) => ({
      type: i.type,
      region: i.region,
      date: i.date,
      facility: i.facility,
      finding: i.finding,
      status: i.status,
    }));

  const langMeta = SUPPORTED_LANGUAGES.find((l) => l.code === language);
  const isRtl = !!langMeta?.rtl;

  // M2: serialise visits for the edge function (snake-case-light, but keep camelCase for payload).
  const visitsPayload = (input.visits || []).map((v) => ({
    visitDate: v.visitDate,
    facilityName: v.facilityName,
    facilityCountry: v.facilityCountry,
    reasonForVisit: v.reasonForVisit,
    investigationsPerformed: v.investigationsPerformed || [],
    findings: v.findings,
    diagnosis: v.diagnosis,
    medicationsPrescribed: v.medicationsPrescribed || [],
    followUpRecommendations: v.followUpRecommendations || [],
  }));

  const baseStrings = getStrings(language);
  const finalPayload = {
    patient,
    counts,
    currentMedications: currentMeds,
    allergies,
    highlights,
    visits: visitsPayload,
    medicationsTable,
    bloodTable,
    imagingTable,
    language,
    isRtl,
    generatedAt: new Date().toLocaleDateString(language === "en" ? "en-GB" : language, {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    strings: {
      patientSummary: baseStrings.patientSummary,
      atAGlance: baseStrings.atAGlance(counts.documents, counts.countries, counts.yearsSpan),
      currentMedications: baseStrings.currentMedications,
      knownAllergies: baseStrings.knownAllergies,
      chronicConditions: baseStrings.chronicConditions,
      clinicalHighlights: baseStrings.clinicalHighlights,
      none: baseStrings.none,
      footerNote: baseStrings.footerNote,
      disclaimer: baseStrings.disclaimer,
      visitHistory: baseStrings.visitHistory,
      visitHistorySubtitle: baseStrings.visitHistorySubtitle,
      reasonForVisit: baseStrings.reasonForVisit,
      investigations: baseStrings.investigations,
      findings: baseStrings.findings,
      diagnosis: baseStrings.diagnosis,
      medicationsPrescribed: baseStrings.medicationsPrescribed,
      followUp: baseStrings.followUp,
      noVisits: baseStrings.noVisits,
      medicationsTitle: baseStrings.medicationsTitle,
      medicationsSubtitle: baseStrings.medicationsSubtitle,
      medColName: baseStrings.medColName,
      medColDose: baseStrings.medColDose,
      medColFrequency: baseStrings.medColFrequency,
      medColPrescriber: baseStrings.medColPrescriber,
      medColStarted: baseStrings.medColStarted,
      medColStatus: baseStrings.medColStatus,
      medActive: baseStrings.medActive,
      medInactive: baseStrings.medInactive,
      noMedications: baseStrings.noMedications,
      bloodResultsTitle: baseStrings.bloodResultsTitle,
      bloodResultsSubtitle: baseStrings.bloodResultsSubtitle,
      bloodColMarker: baseStrings.bloodColMarker,
      bloodColValue: baseStrings.bloodColValue,
      bloodColRange: baseStrings.bloodColRange,
      bloodColStatus: baseStrings.bloodColStatus,
      bloodColDate: baseStrings.bloodColDate,
      bloodStatusNormal: baseStrings.bloodStatusNormal,
      bloodStatusFlagged: baseStrings.bloodStatusFlagged,
      bloodStatusCritical: baseStrings.bloodStatusCritical,
      noBloodResults: baseStrings.noBloodResults,
      imagingTitle: baseStrings.imagingTitle,
      imagingSubtitle: baseStrings.imagingSubtitle,
      imagingFinding: baseStrings.imagingFinding,
      imagingNormal: baseStrings.imagingNormal,
      imagingFlagged: baseStrings.imagingFlagged,
      noImaging: baseStrings.noImaging,
    },
  };

  const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL;
  const SUPABASE_ANON = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY;
  const session = (await supabase.auth.getSession()).data.session;

  const res = await fetch(`${SUPABASE_URL}/functions/v1/render-export-pdf`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      apikey: SUPABASE_ANON,
      Authorization: `Bearer ${session?.access_token || SUPABASE_ANON}`,
    },
    body: JSON.stringify(finalPayload),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`PDF render failed: ${res.status} ${errText}`);
  }

  const blob = await res.blob();
  onProgress?.("ready");
  return blob;
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
