import jsPDF from "jspdf";
import "jspdf-autotable";
import autoTable from "jspdf-autotable";
import type { BloodResult, ImagingResult, Medication, Allergy, Document as VaultDoc, Alert } from "@/store/vaultStore";

interface VaultData {
  bloodResults: BloodResult[];
  imagingResults: ImagingResult[];
  medications: Medication[];
  documents: VaultDoc[];
  alerts: Alert[];
  allergies: Allergy[];
}

const FOOTER_TEXT = "This document was generated by Vault Health Intelligence. It contains information extracted from uploaded medical documents. It is not a substitute for original clinical records.";

function addHeader(doc: jsPDF, patientName: string, pageNum: number, totalPages: number) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFontSize(10);
  doc.setTextColor(180, 160, 100);
  doc.setFont("helvetica", "bold");
  doc.text("VAULT", 20, 15);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(patientName, 60, 15);
  doc.text(`Page ${pageNum} of ${totalPages}`, w - 20, 15, { align: "right" });
  doc.setDrawColor(220, 220, 220);
  doc.line(20, 18, w - 20, 18);
}

function addFooter(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(220, 220, 220);
  doc.line(20, h - 20, w - 20, h - 20);
  doc.setFontSize(6);
  doc.setTextColor(150, 150, 150);
  const lines = doc.splitTextToSize(FOOTER_TEXT, w - 40);
  doc.text(lines, 20, h - 15);
}

function applyHeadersAndFooters(doc: jsPDF, patientName: string) {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addHeader(doc, patientName, i, totalPages);
    addFooter(doc);
  }
}

function addCoverPage(doc: jsPDF, patientName: string, dob: string) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  
  doc.setFontSize(32);
  doc.setTextColor(180, 160, 100);
  doc.setFont("helvetica", "bold");
  doc.text("VAULT", w / 2, h / 2 - 40, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.setFont("helvetica", "normal");
  doc.text("Health Intelligence", w / 2, h / 2 - 28, { align: "center" });

  doc.setDrawColor(180, 160, 100);
  doc.line(w / 2 - 30, h / 2 - 20, w / 2 + 30, h / 2 - 20);

  doc.setFontSize(16);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "bold");
  doc.text(patientName, w / 2, h / 2, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  if (dob) doc.text(`Date of Birth: ${dob}`, w / 2, h / 2 + 12, { align: "center" });
  doc.text(`Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`, w / 2, h / 2 + 24, { align: "center" });
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "bold");
  doc.text(title, 20, y);
  doc.setDrawColor(180, 160, 100);
  doc.line(20, y + 2, 80, y + 2);
  return y + 10;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number = 30): number {
  if (y + needed > doc.internal.pageSize.getHeight() - 30) {
    doc.addPage();
    return 28;
  }
  return y;
}

function addAlerts(doc: jsPDF, alerts: Alert[], y: number): number {
  if (alerts.length === 0) return y;
  y = checkPageBreak(doc, y, 20 + alerts.length * 8);
  y = addSectionTitle(doc, "Key Alerts", y);
  doc.setFontSize(9);
  alerts.forEach((a) => {
    y = checkPageBreak(doc, y);
    doc.setTextColor(a.type === "critical" ? 200 : 180, a.type === "critical" ? 50 : 120, 50);
    doc.text(`${a.type === "critical" ? "⚠" : "●"} ${a.message}`, 22, y);
    y += 7;
  });
  return y + 4;
}

function addBloodResults(doc: jsPDF, results: BloodResult[], y: number): number {
  if (results.length === 0) return y;
  doc.addPage();
  y = 28;
  y = addSectionTitle(doc, "Blood Results", y);

  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [["Marker", "Value", "Unit", "Range", "Status", "Source", "Date"]],
    body: results.map((r) => [r.marker, String(r.value), r.unit, r.range, r.status, r.source, r.date]),
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [180, 160, 100], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 4) {
        const val = String(data.cell.raw);
        if (val === "critical") data.cell.styles.textColor = [200, 50, 50];
        else if (val === "flagged") data.cell.styles.textColor = [200, 150, 50];
      }
    },
  });

  return (doc as any).lastAutoTable?.finalY + 8 || y + 20;
}

function addImaging(doc: jsPDF, results: ImagingResult[], y: number): number {
  if (results.length === 0) return y;
  doc.addPage();
  y = 28;
  y = addSectionTitle(doc, "Imaging Findings", y);
  doc.setFontSize(9);
  results.forEach((r) => {
    y = checkPageBreak(doc, y, 25);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text(`${r.type} — ${r.region}`, 22, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`${r.facility} · ${r.date}`, 22, y);
    y += 6;
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(r.finding || "No findings recorded", 160);
    doc.text(lines, 22, y);
    y += lines.length * 5 + 8;
  });
  return y;
}

function addMedications(doc: jsPDF, meds: Medication[], y: number): number {
  if (meds.length === 0) return y;
  doc.addPage();
  y = 28;
  y = addSectionTitle(doc, "Medications", y);

  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [["Name", "Dose", "Frequency", "Prescriber", "Facility", "Date", "Active"]],
    body: meds.map((m) => [m.name, m.dose, m.frequency, m.prescriber, m.facility, m.date, m.active ? "Yes" : "No"]),
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [180, 160, 100], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 248] },
  });

  return (doc as any).lastAutoTable?.finalY + 8 || y + 20;
}

function addAllergies(doc: jsPDF, allergies: Allergy[], y: number): number {
  if (allergies.length === 0) return y;
  y = checkPageBreak(doc, y, 20 + allergies.length * 10);
  y = addSectionTitle(doc, "Allergies", y);

  // Red bordered box
  const boxH = 10 + allergies.length * 8;
  doc.setDrawColor(220, 60, 60);
  doc.setLineWidth(0.5);
  doc.roundedRect(20, y - 2, doc.internal.pageSize.getWidth() - 40, boxH, 2, 2);

  doc.setFontSize(9);
  allergies.forEach((a) => {
    doc.setTextColor(180, 40, 40);
    doc.setFont("helvetica", "bold");
    doc.text(a.substance, 25, y + 5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`${a.reaction} · Severity: ${a.severity}`, 80, y + 5);
    y += 8;
  });

  return y + 12;
}

function addDocumentsList(doc: jsPDF, docs: VaultDoc[], y: number): number {
  if (docs.length === 0) return y;
  doc.addPage();
  y = 28;
  y = addSectionTitle(doc, "Uploaded Documents", y);

  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [["Document Name", "Type", "Facility", "Country", "Date", "Pages", "Extracted"]],
    body: docs.map((d) => [d.name, d.type, d.facility, d.country, d.date, String(d.pages), d.extracted ? "Yes" : "No"]),
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [180, 160, 100], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 248] },
  });

  return (doc as any).lastAutoTable?.finalY + 8 || y + 20;
}

export function generateFullBriefPDF(data: VaultData, patientName: string, dob: string) {
  const doc = new jsPDF();
  addCoverPage(doc, patientName, dob);

  doc.addPage();
  let y = 28;
  y = addAlerts(doc, data.alerts, y);
  y = addAllergies(doc, data.allergies, y);
  y = addBloodResults(doc, data.bloodResults, y);
  y = addImaging(doc, data.imagingResults, y);
  y = addMedications(doc, data.medications, y);
  addDocumentsList(doc, data.documents, y);

  applyHeadersAndFooters(doc, patientName);
  doc.save(`Vault_Health_Brief_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function generateCategoryPDF(
  data: VaultData,
  patientName: string,
  dob: string,
  categories: { blood: boolean; imaging: boolean; medications: boolean; allergies: boolean; documents: boolean }
) {
  const doc = new jsPDF();
  addCoverPage(doc, patientName, dob);

  doc.addPage();
  let y = 28;
  y = addAlerts(doc, data.alerts, y);
  if (categories.allergies) y = addAllergies(doc, data.allergies, y);
  if (categories.blood) y = addBloodResults(doc, data.bloodResults, y);
  if (categories.imaging) y = addImaging(doc, data.imagingResults, y);
  if (categories.medications) y = addMedications(doc, data.medications, y);
  if (categories.documents) addDocumentsList(doc, data.documents, y);

  applyHeadersAndFooters(doc, patientName);
  doc.save(`Vault_Export_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function generateSelectionPDF(data: VaultData, patientName: string, dob: string, selectedIds: Set<string>) {
  const selectedDocs = data.documents.filter((d) => selectedIds.has(d.id));
  const doc = new jsPDF();
  addCoverPage(doc, patientName, dob);

  doc.addPage();
  let y = 28;
  y = addSectionTitle(doc, "Selected Documents", y);

  selectedDocs.forEach((d) => {
    y = checkPageBreak(doc, y, 30);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text(d.name, 22, y);
    y += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(`${d.type} · ${d.facility} · ${d.country} · ${d.date} · ${d.pages} page(s)`, 22, y);
    y += 6;
    if (d.summary) {
      doc.setTextColor(80, 80, 80);
      const summaryText = Array.isArray(d.summary) ? d.summary.join(". ") : String(d.summary);
      const lines = doc.splitTextToSize(summaryText, 160);
      doc.text(lines, 22, y);
      y += lines.length * 5;
    }
    if (d.aiNote) {
      doc.setTextColor(100, 100, 180);
      doc.setFont("helvetica", "italic");
      const noteLines = doc.splitTextToSize(`AI Note: ${d.aiNote}`, 160);
      doc.text(noteLines, 22, y);
      y += noteLines.length * 5;
    }
    y += 8;
  });

  applyHeadersAndFooters(doc, patientName);
  doc.save(`Vault_Selection_${new Date().toISOString().split("T")[0]}.pdf`);
}
