// Builds the M1 (Patient Summary) + M2 (Visit History) payload for the v2 PDF engine.
// Translates clinical data via the existing translate-export edge function (24h cached),
// derives the at-a-glance counts and Clinical Highlights, deduplicates imaging studies,
// then POSTs to render-export-pdf.

import { supabase } from "@/integrations/supabase/client";
import type { VaultData } from "@/lib/pdfExport";
import type { Visit, ImagingLinkOverride } from "@/store/vaultStore";
import { SUPPORTED_LANGUAGES } from "@/lib/supportedLanguages";
import { dedupeImaging } from "@/lib/visitDedupe";

export type ProgressPhase = "translating" | "rendering" | "ready";

export interface PatientSummaryInput {
  data: VaultData;
  visits?: Visit[];
  imagingOverrides?: ImagingLinkOverride[];
  patient: {
    fullName: string;
    dob?: string;
    biologicalSex?: string;
    nationality?: string;
    bloodType?: string;
    chronicConditions?: string;
  };
  language: string;
  onProgress?: (phase: ProgressPhase) => void;
}

// ---------- Localised UI strings (extended for M2 — Visit History) ----------
type StringPack = {
  patientSummary: string;
  atAGlance: (n: number, c: number, y: number) => string;
  currentMedications: string;
  knownAllergies: string;
  chronicConditions: string;
  clinicalHighlights: string;
  none: string;
  page: (i: number, total: number) => string;
  footerNote: string;
  disclaimer: string;
  visitHistory: string;
  visitHistorySubtitle: string;
  reasonForVisit: string;
  investigations: string;
  findings: string;
  diagnosis: string;
  medicationsPrescribed: string;
  followUp: string;
  noVisits: string;
};

const STRINGS: Record<string, StringPack> = {
  en: {
    patientSummary: "Patient Summary",
    atAGlance: (n, c, y) =>
      `This health record contains ${n} document${n === 1 ? "" : "s"} from ${c} ${c === 1 ? "country" : "countries"} spanning ${y} year${y === 1 ? "" : "s"}.`,
    currentMedications: "Current Medications",
    knownAllergies: "Known Allergies",
    chronicConditions: "Chronic Conditions",
    clinicalHighlights: "Clinical Highlights",
    none: "None recorded.",
    page: (i, total) => `Page ${i} of ${total}`,
    footerNote: "Generated by RinVita",
    disclaimer:
      "Generated by RinVita Health Intelligence. This document contains extracted health data and is not a substitute for original clinical records. RinVita is not a medical device. ICO Registration ZC123014.",
  },
  ar: {
    patientSummary: "ملخص المريض",
    atAGlance: (n, c, y) => `يحتوي هذا السجل الصحي على ${n} مستند من ${c} دولة على مدى ${y} سنوات.`,
    currentMedications: "الأدوية الحالية",
    knownAllergies: "الحساسية المعروفة",
    chronicConditions: "الحالات المزمنة",
    clinicalHighlights: "الملاحظات السريرية",
    none: "لا يوجد.",
    page: (i, total) => `صفحة ${i} من ${total}`,
    footerNote: "تم إنشاؤه بواسطة RinVita",
    disclaimer:
      "تم إنشاؤه بواسطة RinVita Health Intelligence. هذه الوثيقة تحتوي على بيانات صحية مستخرجة وليست بديلاً عن السجلات السريرية الأصلية. RinVita ليست جهازًا طبيًا. تسجيل ICO ZC123014.",
  },
  es: {
    patientSummary: "Resumen del paciente",
    atAGlance: (n, c, y) =>
      `Este registro de salud contiene ${n} documento${n === 1 ? "" : "s"} de ${c} ${c === 1 ? "país" : "países"} a lo largo de ${y} año${y === 1 ? "" : "s"}.`,
    currentMedications: "Medicación actual",
    knownAllergies: "Alergias conocidas",
    chronicConditions: "Condiciones crónicas",
    clinicalHighlights: "Aspectos clínicos destacados",
    none: "Ninguno registrado.",
    page: (i, total) => `Página ${i} de ${total}`,
    footerNote: "Generado por RinVita",
    disclaimer:
      "Generado por RinVita Health Intelligence. Este documento contiene datos de salud extraídos y no sustituye los registros clínicos originales. RinVita no es un dispositivo médico. Registro ICO ZC123014.",
  },
  fr: {
    patientSummary: "Résumé du patient",
    atAGlance: (n, c, y) =>
      `Ce dossier médical contient ${n} document${n === 1 ? "" : "s"} provenant de ${c} pays sur ${y} an${y === 1 ? "" : "s"}.`,
    currentMedications: "Médicaments actuels",
    knownAllergies: "Allergies connues",
    chronicConditions: "Affections chroniques",
    clinicalHighlights: "Points cliniques marquants",
    none: "Aucun enregistré.",
    page: (i, total) => `Page ${i} sur ${total}`,
    footerNote: "Généré par RinVita",
    disclaimer:
      "Généré par RinVita Health Intelligence. Ce document contient des données de santé extraites et ne remplace pas les dossiers cliniques originaux. RinVita n'est pas un dispositif médical. Enregistrement ICO ZC123014.",
  },
};

function getStrings(lang: string): StringPack {
  return STRINGS[lang] || STRINGS.en;
}

// ---------- Derivations ----------
function computeCounts(data: VaultData): { documents: number; countries: number; yearsSpan: number } {
  const documents = data.documents.length;
  const countries = new Set(
    data.documents.map((d) => d.country).filter((c) => c && c.trim().length > 0),
  ).size;

  const allDates = [
    ...data.documents.map((d) => d.date),
    ...data.bloodResults.map((b) => b.date),
    ...data.imagingResults.map((i) => i.date),
  ]
    .filter(Boolean)
    .map((d) => new Date(d as string).getFullYear())
    .filter((y) => !Number.isNaN(y) && y > 1900);

  const yearsSpan = allDates.length === 0 ? 0 : Math.max(1, Math.max(...allDates) - Math.min(...allDates) + 1);

  return { documents, countries, yearsSpan };
}

function deriveHighlights(data: VaultData): string[] {
  const out: string[] = [];

  // Out-of-range blood markers, most recent first.
  const flagged = data.bloodResults
    .filter((r) => r.status === "flagged" || r.status === "critical")
    .sort((a, b) => (b.date || "").localeCompare(a.date || ""));

  for (const r of flagged.slice(0, 4)) {
    const dateBit = r.date ? ` on ${r.date}` : "";
    const rangeBit = r.range ? ` (reference ${r.range})` : "";
    out.push(`${r.marker} ${r.value} ${r.unit} — out of range${rangeBit}${dateBit}.`);
  }

  // Imaging findings flagged non-normal.
  const flaggedImaging = data.imagingResults
    .filter((i) => i.status === "flagged")
    .sort((a, b) => (b.date || "").localeCompare(a.date || ""));

  for (const img of flaggedImaging.slice(0, Math.max(0, 5 - out.length))) {
    const dateBit = img.date ? ` (${img.date})` : "";
    out.push(`${img.type} ${img.region} — ${img.finding}${dateBit}.`);
  }

  return out.slice(0, 5);
}

// ---------- Translation ----------
async function translateIfNeeded(data: VaultData, language: string): Promise<VaultData> {
  if (!language || language === "en") return data;
  try {
    const { data: result, error } = await supabase.functions.invoke("translate-export", {
      body: { payload: data, targetLanguage: language },
    });
    if (error) throw new Error(error.message || "Translation failed");
    return (result?.translated as VaultData) || data;
  } catch (err) {
    console.warn("translate-export failed, falling back to source data:", err);
    return data;
  }
}

// ---------- Public entry ----------
export async function generatePatientSummaryV2(input: PatientSummaryInput): Promise<Blob> {
  const { data, patient, language, onProgress } = input;

  onProgress?.("translating");
  const translated = await translateIfNeeded(data, language);

  onProgress?.("rendering");

  const counts = computeCounts(translated);
  const highlights = deriveHighlights(translated);
  const currentMeds = translated.medications
    .filter((m) => m.active !== false)
    .map((m) => ({ name: m.name, dose: m.dose, frequency: m.frequency }));
  const allergies = translated.allergies.map((a) => ({
    substance: a.substance,
    severity: a.severity,
    reaction: a.reaction,
  }));

  const langMeta = SUPPORTED_LANGUAGES.find((l) => l.code === language);
  const isRtl = !!langMeta?.rtl;

  const baseStrings = getStrings(language);
  const finalPayload = {
    patient,
    counts,
    currentMedications: currentMeds,
    allergies,
    highlights,
    language,
    isRtl,
    generatedAt: new Date().toLocaleDateString(language === "en" ? "en-GB" : language, {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    strings: {
      patientSummary: baseStrings.patientSummary,
      atAGlance: baseStrings.atAGlance(counts.documents, counts.countries, counts.yearsSpan),
      currentMedications: baseStrings.currentMedications,
      knownAllergies: baseStrings.knownAllergies,
      chronicConditions: baseStrings.chronicConditions,
      clinicalHighlights: baseStrings.clinicalHighlights,
      none: baseStrings.none,
      footerNote: baseStrings.footerNote,
      disclaimer: baseStrings.disclaimer,
    },
  };

  const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL;
  const SUPABASE_ANON = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY;
  const session = (await supabase.auth.getSession()).data.session;

  const res = await fetch(`${SUPABASE_URL}/functions/v1/render-export-pdf`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      apikey: SUPABASE_ANON,
      Authorization: `Bearer ${session?.access_token || SUPABASE_ANON}`,
    },
    body: JSON.stringify(finalPayload),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`PDF render failed: ${res.status} ${errText}`);
  }

  const blob = await res.blob();
  onProgress?.("ready");
  return blob;
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
