// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-documents.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-documents.ts
var list_documents_default = defineTool({
  name: "list_documents",
  title: "List medical documents",
  description: "List the signed-in user's uploaded medical documents (name, type, date, facility, country, language and processing status).",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Optional text to match against the document name."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of documents to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("documents").select(
      "id,name,type,date,facility,country,original_language,translated_language_code,pages,processing_status,created_at"
    ).order("date", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-document.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_document_default = defineTool2({
  name: "get_document",
  title: "Get a medical document",
  description: "Fetch one of the signed-in user's documents by id, including the AI summary, original text and translated text.",
  inputSchema: {
    document_id: z2.string().uuid().describe("The document id returned by list_documents."),
    include_full_text: z2.boolean().default(false).describe("Include the full original and translated document text (can be long).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ document_id, include_full_text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const columns = include_full_text ? "id,name,type,date,facility,country,original_language,summary,ai_note,content_original,content_translated,processing_status" : "id,name,type,date,facility,country,original_language,summary,ai_note,processing_status";
    const { data, error } = await supabaseForUser(ctx).from("documents").select(columns).eq("id", document_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Document not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { document: data }
    };
  }
});

// src/lib/mcp/tools/list-medications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_medications_default = defineTool3({
  name: "list_medications",
  title: "List medications",
  description: "List the signed-in user's medications with dose, frequency, prescriber and active status.",
  inputSchema: {
    active_only: z3.boolean().default(true).describe("Only return medications currently marked as active.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("medications").select("id,name,dose,frequency,prescriber,facility,date,active,source").order("date", { ascending: false, nullsFirst: false });
    if (active_only !== false) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { medications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blood-results.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_blood_results_default = defineTool4({
  name: "list_blood_results",
  title: "List blood results",
  description: "List the signed-in user's blood test markers with value, unit, reference range and in/out-of-range status.",
  inputSchema: {
    marker: z4.string().trim().min(1).optional().describe("Optional marker name filter, e.g. 'Haemoglobin'."),
    abnormal_only: z4.boolean().default(false).describe("Only return markers whose status is not 'normal'."),
    limit: z4.number().int().min(1).max(200).default(50).describe("Maximum number of rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ marker, abnormal_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("blood_results").select("id,marker,value,unit,range,status,date,source").order("date", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (marker) query = query.ilike("marker", `%${marker}%`);
    if (abnormal_only) query = query.neq("status", "normal");
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { blood_results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-allergies.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_allergies_default = defineTool5({
  name: "list_allergies",
  title: "List allergies",
  description: "List the signed-in user's recorded allergies with substance, reaction and severity.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("allergies").select("id,substance,reaction,severity,source,created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { allergies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-visits.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_visits_default = defineTool6({
  name: "list_visits",
  title: "List medical visits",
  description: "List the signed-in user's medical visits (facility, country, reason, diagnosis, findings and follow-up recommendations).",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(25).describe("Maximum number of visits to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("visits").select(
      "id,visit_date,facility_name,facility_country,reason_for_visit,diagnosis,findings,investigations_performed,medications_prescribed,follow_up_recommendations"
    ).order("visit_date", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { visits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-health-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_health_summary_default = defineTool7({
  name: "get_health_summary",
  title: "Get health summary",
  description: "Return a clinician-ready overview of the signed-in user: active medications, allergies, abnormal blood markers, recent visits and document counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [meds, allergies, bloods, visits, documents] = await Promise.all([
      supabase.from("medications").select("name,dose,frequency,active").eq("active", true),
      supabase.from("allergies").select("substance,reaction,severity"),
      supabase.from("blood_results").select("marker,value,unit,range,status,date").neq("status", "normal").limit(25),
      supabase.from("visits").select("visit_date,facility_name,facility_country,reason_for_visit,diagnosis").order("visit_date", { ascending: false, nullsFirst: false }).limit(5),
      supabase.from("documents").select("id", { count: "exact", head: true })
    ]);
    const firstError = [meds, allergies, bloods, visits, documents].find((r) => r.error)?.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const summary = {
      active_medications: meds.data ?? [],
      allergies: allergies.data ?? [],
      abnormal_blood_markers: bloods.data ?? [],
      recent_visits: visits.data ?? [],
      document_count: documents.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gnxctlydesugjdwbavdx";
var mcp_default = defineMcp({
  name: "global-health-vault",
  title: "Global Health Vault",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's RinVita health vault. Use get_health_summary for an overview, list_documents/get_document for uploaded and translated medical records, and list_medications, list_blood_results, list_allergies and list_visits for structured data. Never fabricate clinical information: report only what these tools return.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_health_summary_default,
    list_documents_default,
    get_document_default,
    list_medications_default,
    list_blood_results_default,
    list_allergies_default,
    list_visits_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
